### ISSUE TITLE
Examples for custom functions

### ISSUE THREAD

**Issue by andupotorac** [amoffat/manifest#3]
Hey there. Where could we define new functions the LLM should call? For example our current system prompts include examples and are quite large in length. I looked though the files quickly and didn't find the spot where yours are defined.

**Comment by amoffat** [comment]
Hi @andupotorac. I'm not sure I understand the question. You define the functions wherever you want, just as long as it's decorated with `@ai`. The docstring of the function is essentially the prompt.

**Comment by andupotorac** [comment]
"The docstring of the function is essentially the prompt." - thought this might be the case. Thanks a lot!
